### PR TITLE
Deny replication of local databases

### PR DESCRIPTION
**Pull request by iilyak**
Disable replication of local databases in order to prevent MT customers
from replication or modification of special local databases such as 'dbs'.

The implementation is protected by a feature flag.
The default value is 'allow'. Possible values for 'local_dbs' flag are:
 - deny
 - allow

Use following to deny access

    [replicator]
    local_dbs = deny

BugzID: 91980

### CODE REVIEW

**Comment by iilyak** [comment]
The logs have following entries:
```
<149>1 2017-08-31T23:09:58.759416Z MacBook-Pro.local twig <0.279.0> -------- - Maybe starting '964a6c94d03e7350cdc495db56000a4a' as I'm the owner
<147>1 2017-08-31T23:09:58.759813Z MacBook-Pro.local twig <0.279.0> -------- - Replication manager, error processing document `964a6c94d03e7350cdc495db56000a4a`: {throw,{forbidden,<<"replication of local dbs is not supported">>}}
```

**Comment by iilyak** [comment]
I'll update the error message to include replication id and db

**Comment by rnewson** [comment]
Could we instead treat "foo" as referring to a clustered database if the replicator doc is inside a shard but a local one when it's not? That way the correct semantics are honored as well as fixing the security issue (since access will be blocked to the clustered database). That is, implement an equivalent of chttpd.erl's possibly_hack function.

**Comment by iilyak** [comment]
stale PR replaced with https://github.com/cloudant/couch_replicator/pull/81

**Pull request closed without merging**
